### ISSUE TITLE
What is the correct license?

### ISSUE THREAD

**Issue by roptat** [janestreet/variantslib#2]
Hi,

it seems that this repo has a LICENSE file that states that the license is MIT, but the opam file has Apache-2.0, and that is the license advertised by opam, so I'm a bit confused. What is the correct license? Could you fix that? It seems that this happens in a few other of your projects.

Thanks!

**Comment by ghost** [comment]
IIRC, the last release (v0.11) was still published under the Apache 2.0 license. In any case, the LICENSE.txt file in variantslib v0.11 is indeed the Apache 2.0 license. If you look in this git repository, the license field of the opam file is now MIT.

**Comment by roptat** [comment]
Ha indeed, I guess I was looking at different revisions of the repository then. Thanks for your quick answer!
